version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      TZ: Asia/Tokyo
      FILES_DIR: /var/lib/tfs
      EXPIRATION_DAYS: ${EXPIRATION_DAYS:-1}
    volumes:
      - tfs-data:/var/lib/tfs
    ports:
      - 80:80

  db:
    image: mysql:8.0
    environment:
      TZ: Asia/Tokyo
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: tfs
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  tfs-data:
  mysql-data:
