version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - TZ=Asia/Tokyo
      - TFS_FILES_DIR=/var/lib/tfs
      - TFS_PAGE_TITLE
      - TFS_EXPIRATION_DAYS
      - TFS_DISABLE_DOCS=True
    volumes:
      - tfs-data:/var/lib/tfs
    ports:
      - 80:80
    restart: always

  db:
    image: mysql:8.0
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=tfs
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always

volumes:
  tfs-data:
  mysql-data:
