version: '3.3'
services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    depends_on:
      - db
    command: /start-reload.sh
    environment:
      - TZ=Asia/Tokyo
      - TFS_FILES_DIR=/var/lib/tfs
      - TFS_PAGE_TITLE
      - TFS_FILE_EXPIRE_DAYS
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - ..:/app
      - tfs-data:/var/lib/tfs
    ports:
      - 8080:80

  db:
    image: mysql:8.0
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=tfs
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  tfs-data:
  mysql-data:
