version: '3.3'
services:
  nginx:
    ports:
      - 8080:80

  app:
    build:
      dockerfile: ../.devcontainer/Dockerfile
    command: /start-reload.sh
    environment:
      - TFS_ENABLE_DOCS=True
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - type: bind
        source: ./app
        target: /app
